name: cs442_mp1
description: CS 442 MP1 - Profile information page
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

flutter:
  uses-material-design: true
  assets:
    - assets/images/popeye.png
    - assets/images/music.jpeg
    - assets/images/cycling.png
    - assets/images/photo.png
    - assets/images/globe.png
    - assets/images/meditate.png
    - assets/images/nightlife.png
    - assets/images/mountain.png
    - assets/images/cook.png
